[package]
name = "sudoku_solver"
version = "0.1.0"
edition = "2021"

[dependencies]
crossterm = "0.27.0"
fakeit = "1.2.0"
itertools = "0.13.0"
ratatui = "0.27.0"
unicode-width = "0.1.13"

[target.x86_64-pc-windows-gnu]
linker = "x86_64-w64-mingw32-gcc"
